### ISSUE TITLE
Index all

### ISSUE THREAD

**Issue by 304NotModified** [messagetemplates/grammar#2]
it should be all index or all named?

Currently it is:

```
Property ::=  '{' ('@' | '$')? (PropertyName | Index) (',' Alignment)? (':' Format)? '}'
```

**Comment by 304NotModified** [comment]
proposal:

```
Text ::= ([^\{] | '{{' | '}}')+
PropertyName ::= [0-9A-z_]+
Index::= [0-9]+
Format ::= [^\{]+
Template ::= NamedTemplate | IndexedTemplate
NamedTemplate ::= (Text | NamedProperty)*
IndexedTemplate ::= (Text | IndexedProperty)*
NamedProperty ::=  '{' ('@' | '$')? PropertyName  (',' Alignment)? (':' Format)? '}'
IndexedProperty ::=  '{' ('@' | '$')? Index  (',' Alignment)? (':' Format)? '}'
Alignment ::= '-'?[0-9]+

```

(mabye removing duplication)

**Comment by nblumhardt** [comment]
Though it's treated as a named template, Serilog doesn't disallow:

```csharp
"Hello {0} at {Time}"
```

The question here probably comes down to whether we want the grammar to identify all parseable message templates, or all _valid_ message templates.

I am inclined to agree with your proposal here on the grounds that we're defining a safe, shared, reasonably-portable subset - perhaps it's fine if different implementations are more permissive as a user-friendly concession, but the diagram would be clearer if it showed the intended, valid syntax.

I guess this is similar to the case of JSON.NET - it accepts everything from the (minimal, strict) JSON spec, as well as some extensions like comments and un-quoted property names.

Would you (and @adamchester @jods4) agree that the goal of the grammar here and the (currently JSON) test cases are to cover the valid subset? We can keep the C# and F# "reference" implementations permissive without being at odds with that.

**Comment by nblumhardt** [comment]
This one's a bit stale now :-) 👋

**Comment by 304NotModified** [comment]
Just a bit 😆
