### ISSUE TITLE
Generate Railroad diagram

### ISSUE THREAD

**Issue by 304NotModified** [messagetemplates/grammar#3]
Like this one: http://www.bottlecaps.de/rr/ui

![image](https://cloud.githubusercontent.com/assets/5808377/17640041/761ccd12-60f9-11e6-99de-9a472fee5e17.png)

**Comment by nblumhardt** [comment]
:+1: .. and include in the `#Syntax` section on https://messagetemplates.org.

**Comment by nblumhardt** [comment]
Done: https://messagetemplates.org/
